query Babies {
  babies {
    ...AllBabyFields
  }
}

query Baby($id: ID!) {
  baby(id: $id) {
    ...AllBabyFields
  }
}

mutation CreateBaby($input: CreateBabyInput!) {
  createBaby(input: $input) {
    ...AllBabyFields
  }
}

mutation UpdateBaby($input: UpdateBabyInput!) {
  updateBaby(input: $input) {
    ...AllBabyFields
  }
}

mutation DeleteBaby($id: ID!) {
  deleteBaby(id: $id) {
    id
  }
}

mutation Unbirth($id: ID!) {
  unbirth(id: $id) {
    ...AllBabyFields
  }
}

mutation Birth($id: ID!, $birthdate: String) {
  birth(id: $id, birthdate: $birthdate) {
    ...AllBabyFields
  }
}

fragment AllBabyFields on Baby {
  id
  name
  alternativeName
  nickname
  birthdate
  birthTime
  dueDate
  gender
  father {
    id
    name
  }
  mother {
    id
    name
  }
  createdAt
  updatedAt
}
