query MilestoneAchievements($babyId: ID!) {
  milestoneAchievements(babyId: $babyId) {
    id
    timestamp
    milestone {
      id
    }
  }
}

mutation LogMilestoneAchievement($babyId: ID!, $milestoneId: ID!) {
  logMilestoneAchievement(babyId: $babyId, milestoneId: $milestoneId) {
    id
    timestamp
    milestone {
      id
    }
  }
}
mutation UnachieveMilestone($id: ID!) {
  deleteMilestoneAchievement(id: $id) {
    id
  }
}
