query RecentSleeps($babyId: ID!) {
  recentSleeps(babyId: $babyId) {
    ...AllSleepFields
  }
}

mutation UpdateSleep($input: UpdateSleepInput!) {
  updateSleep(input: $input) {
    ...AllSleepFields
  }
}

mutation CreateSleep($input: CreateSleepInput!) {
  createSleep(input: $input) {
    ...AllSleepFields
  }
}

mutation DeleteSleep($id: ID!) {
  deleteSleep(id: $id) {
    id
  }
}
fragment AllSleepFields on Sleep {
  id
  wakeReason
  start
  end
  notes
  baby {
    id
  }
  recordedBy {
    id
  }
}
