query UserCount {
  userCount
}

query Users {
  users {
    ...AllUserFields
  }
}

query User($id: ID!) {
  user(id: $id) {
    ...AllUserFields
  }
}
mutation CreateUser($input: CreateUserInput!) {
  createUser(input: $input) {
    ...AllUserFields
  }
}

mutation UpdateUser($input: UpdateUserInput!) {
  updateUser(input: $input) {
    ...AllUserFields
  }
}

mutation DeleteUser($id: ID!) {
  deleteUser(id: $id) {
    id
  }
}

fragment AllUserFields on User {
  id
  username
  email
  name
  isAdmin
  createdAt
  updatedAt
}
