export const month48Milestones = [
  {
    id: '48mSEL1',
    monthsAge: 48,
    category: 'SEL',
    text: 'Pretends to be something else during play (teacher, superhero, dog)',
  },
  {
    id: '48mSEL2',
    monthsAge: 48,
    category: 'SEL',
    text: 'Asks to go play with children if none are around, like “Can I play with Alex?”',
  },
  {
    id: '48mSEL3',
    monthsAge: 48,
    category: 'SEL',
    text: 'Comforts others who are hurt or sad, like hugging a crying friend',
  },
  {
    id: '48mSEL4',
    monthsAge: 48,
    category: 'SEL',
    text: 'Avoids danger, like not jumping from tall heights at the playground',
  },
  {
    id: '48mSEL5',
    monthsAge: 48,
    category: 'SEL',
    text: 'Likes to be a “helper”',
  },
  {
    id: '48mSEL6',
    monthsAge: 48,
    category: 'SEL',
    text: 'Changes behavior based on where she is (place of worship, library, playground)',
  },
  {
    id: '48mLANG1',
    monthsAge: 48,
    category: 'LANG',
    text: 'Says sentences with four or more words',
  },
  {
    id: '48mLANG2',
    monthsAge: 48,
    category: 'LANG',
    text: 'Says some words from a song, story, or nursery rhyme',
  },
  {
    id: '48mLANG3',
    monthsAge: 48,
    category: 'LANG',
    text: 'Talks about at least one thing that happened during his/her day, like “I played soccer.”',
  },
  {
    id: '48mLANG4',
    monthsAge: 48,
    category: 'LANG',
    text: 'Answers simple questions like “What is a coat for?” or “What is a crayon for?”',
  },
  {
    id: '48mCOG1',
    monthsAge: 48,
    category: 'COG',
    text: 'Names a few colors of items',
  },
  {
    id: '48mCOG2',
    monthsAge: 48,
    category: 'COG',
    text: 'Tells what comes next in a well-known story',
  },
  {
    id: '48mCOG3',
    monthsAge: 48,
    category: 'COG',
    text: 'Draws a person with three or more body parts',
  },
  {
    id: '48mPHYS1',
    monthsAge: 48,
    category: 'PHYS',
    text: 'Catches a large ball most of the time',
  },
  {
    id: '48mPHYS2',
    monthsAge: 48,
    category: 'PHYS',
    text: 'Serves himself food or pours water, with adult supervision',
  },
  {
    id: '48mPHYS3',
    monthsAge: 48,
    category: 'PHYS',
    text: 'Unbuttons some buttons',
  },
  {
    id: '48mPHYS4',
    monthsAge: 48,
    category: 'PHYS',
    text: 'Holds crayon or pencil between fingers and thumb (not a fist)',
  },
]
