export const month18Milestones = [
  {
    id: '18mSEL1',
    monthsAge: 18,
    category: 'SEL',
    text: 'Moves away from you, but looks to make sure you are close by',
  },
  {
    id: '18mSEL2',
    monthsAge: 18,
    category: 'SEL',
    text: 'Points to show you something interesting',
  },
  {
    id: '18mSEL3',
    monthsAge: 18,
    category: 'SEL',
    text: 'Puts hands out for you to wash them',
  },
  {
    id: '18mSEL4',
    monthsAge: 18,
    category: 'SEL',
    text: 'Looks at a few pages in a book with you',
  },
  {
    id: '18mSEL5',
    monthsAge: 18,
    category: 'SEL',
    text: 'Helps you dress him/her by pushing arm through sleeve or lifting up foot',
  },
  {
    id: '18mLANG1',
    monthsAge: 18,
    category: 'LANG',
    text: 'Tries to say three or more words besides “mama” or “dada”',
  },
  {
    id: '18mLANG2',
    monthsAge: 18,
    category: 'LANG',
    text: 'Follows one-step directions without any gestures, like giving you the toy when you say, “Give it to me.”',
  },
  {
    id: '18mCOG1',
    monthsAge: 18,
    category: 'COG',
    text: 'Copies you doing chores, like sweeping with a broom',
  },
  {
    id: '18mCOG2',
    monthsAge: 18,
    category: 'COG',
    text: 'Plays with toys in a simple way, like pushing a toy car',
  },
  {
    id: '18mPHYS1',
    monthsAge: 18,
    category: 'PHYS',
    text: 'Walks without holding on to anyone or anything',
  },
  {
    id: '18mPHYS2',
    monthsAge: 18,
    category: 'PHYS',
    text: 'Scribbles',
  },
  {
    id: '18mPHYS3',
    monthsAge: 18,
    category: 'PHYS',
    text: 'Drinks from a cup without a lid and may spill sometimes',
  },
  {
    id: '18mPHYS4',
    monthsAge: 18,
    category: 'PHYS',
    text: 'Feeds herself with her/his fingers',
  },
  {
    id: '18mPHYS5',
    monthsAge: 18,
    category: 'PHYS',
    text: 'Tries to use a spoon',
  },
  {
    id: '18mPHYS6',
    monthsAge: 18,
    category: 'PHYS',
    text: 'Climbs on and off a couch or chair without help',
  },
]
